application: gdev
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /modules
  static_dir: modules

- url: /.*
  script: main.py

builtins:
- datastore_admin: on

